name: hidezign-portfolio
static_sites:
- name: portfolio-web
  build_command: CI=false npm run build
  output_dir: build
  environment_slug: node-js
  routes:
  - path: /
  error_handler:
    error_page: 404.html
    response_code: 404
