name: hidezign-portfolio
static_sites:
- name: portfolio-web
  build_command: npm run build
  output_dir: build
  environment_slug: node-js
  routes:
  - path: /
  error_handler:
    error_page: index.html
    # This ensures React Router handles 404s
    response_code: 200
